### ISSUE TITLE
В админке сломаны все кнопки верхнего меню

### ISSUE THREAD

**Issue by fighter-kit** [Drunyacoder/AtomXCMS-2#4]
Не, я не шучу. Реально так и есть, даже в pre-release такая история наблюдается. Ставил на чистую и даже ничего толком не трогал. Однако ссылки просто поломаны…
![image](https://cloud.githubusercontent.com/assets/3462826/20240595/65abf512-a92d-11e6-8d06-0d4e638ce316.png)

Левое меню при этом работает, но вот верхнее — никак. Удачных исправлений. :)

**Comment by Drunyacoder** [comment]
Хай!

Починил. Посмотреть можно тут "Branch: AtmApi".

**Comment by Drunyacoder** [comment]
Хай.
